### ISSUE TITLE
Missing decrement method in events

### ISSUE THREAD

**Issue by alexsegura** [M6Web/StatsdBundle#61]
The `decrement` method is not managed by the bundle. 

Consider the following configuration:

```yaml
m6_statsd:
  clients:
    default:
      events:
        order.accepted:
          decrement: "orders.waiting"
```

It causes the following error: 
```
Unrecognized option "decrement" under "m6_statsd.clients.default.events.order.accepted"
```

I'll send a pull request shortly.
