### ISSUE TITLE
doc improvment

### ISSUE THREAD

**Issue by omansour** [M6Web/StatsdBundle#7]
in Readme.md a conf exemple is : 

```
clients:
    event:
        console.exception:
            increment: mysite.command.<command.name>.exception
            immediate_send: true
```

Actually, <command.name> will return a string with `:` in. Graphite will cut the node on the left part of the string. 

Any idea to provide a better example ? ping @adriensamson
